package com.skillstorm.spyglass.models;

import java.text.DecimalFormat;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.FutureOrPresent;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "goal")
public class Goal {
	
    private static final DecimalFormat df = new DecimalFormat("0.00");
	
	@Id
	// maybe not generated by identity
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "goal_id")
	private Integer id;
	
	@NotBlank
	@Column
	private String description;
	
	@NotNull
	@Column(name = "amount_needed")
	private double amount_needed;
	
	@NotNull
	@Column(name = "amount_saved")
	private double amount_saved;
	
	@NotNull
	@DateTimeFormat
	@FutureOrPresent
	@Column(name = "complete_by")
	private LocalDate complete_by;

	
	public Goal() {	}
	
	public Goal(int id, String description, double amount_needed, double amount_saved,
			LocalDate complete_by) {
		super();
		this.id = id;
		this.description = description;
		this.amount_needed = Integer.parseInt(df.format(amount_needed));
		this.amount_saved = Integer.parseInt(df.format(amount_saved));
		this.complete_by = complete_by;
	}
	
	public Goal( String description, double amount_needed, double amount_saved,
			LocalDate complete_by) {
		super();
		this.description = description;
		this.amount_needed = Integer.parseInt(df.format(amount_needed));
		this.amount_saved = Integer.parseInt(df.format(amount_saved));
		this.complete_by = complete_by;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the amount_needed
	 */
	public double getAmount_needed() {
		return amount_needed;
	}

	/**
	 * @param amount_needed the amount_needed to set
	 */
	public void setAmount_needed(double amount_needed) {
		this.amount_needed = amount_needed;
	}

	/**
	 * @return the amount_saved
	 */
	public double getAmount_saved() {
		return amount_saved;
	}

	/**
	 * @param amount_saved the amount_saved to set
	 */
	public void setAmount_saved(double amount_saved) {
		this.amount_saved = amount_saved;
	}

	/**
	 * @return the complete_by
	 */
	public LocalDate getComplete_by() {
		return complete_by;
	}

	/**
	 * @param complete_by the complete_by to set
	 */
	public void setComplete_by(LocalDate complete_by) {
		this.complete_by = complete_by;
	}

	@Override
	public String toString() {
		return "Goal [id=" + id + ", description=" + description + ", amount_needed=" + amount_needed
				+ ", amount_saved=" + amount_saved + ", complete_by=" + complete_by + "]";
	}
	

}
